<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>ament_lint_auto_py</name>
  <version>0.20.3</version>
  <description>The auto-magic functions for ease to use of the ament linters in Python.</description>

  <!-- TODO: -->
  <maintainer email="clalancette@gmail.com">Chris Lalancette</maintainer>

  <license>Apache License 2.0</license>

  <author email="audrow@openrobotics.org">Audrow Nash</author>

  <exec_depend>python3-pytest</exec_depend>

  <test_depend>ament_lint_common_py</test_depend>
  <test_depend>ament_mypy</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
