<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>ament_ruff</name>
  <version>0.19.1</version>
  <description>
    The ability to check code for style and syntax conventions and autoformat with ruff.
  </description>

  <maintainer email=""></maintainer>

  <license>Apache License 2.0</license>

  <author email=""></author>
  <author email=""></author>
  <author></author>
  <author></author>
  <author email=""></author>

  <exec_depend>ament_lint</exec_depend>
  <exec_depend>python3-ruff</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
