name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        python-version: ["3.13", "3.14", "pypy-3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: pip install --upgrade pip
      - run: pip install flake8 pydocstyle pytest
      - name: Install ament_copyright
        run: |
          pushd ament_copyright
          pip install --editable .
          popd
      - name: Install ament_flake8
        run: |
          pushd ament_flake8
          pip install --editable .
          popd
      - name: Install ament_pep257
        run: |
          pushd ament_pep257
          pip install --editable .
          popd
      - name: Install ament_xmllint and run pytest
        run: |
          pushd ament_xmllint
          pip install --editable .
          pytest
